all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;port=3306;dbname=orangehrm'
      username: orangehrm
      password: orangehrm
      attributes: { export: tables }
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;port=3306;dbname=test_orangehrm'
      username: orangehrm
      password: orangehrm